### ISSUE TITLE
LSM110A

### ISSUE THREAD

**Issue by tcpipchip** [lucasgranberg/lorawan-pilot#4]
Hi lucas
How is going your time to us port your Rust to our STM32WL55 module (LSM110A) ?

**Comment by lucasgranberg** [comment]
Okay looking around I see you have also asked here https://github.com/ivajloip/rust-lorawan/issues/116.

Basically you can treat  STM32WL55 like an STM32WL5E chip and just use one core. My code does not support AU915 yet.

The rest is up to the module an how it is set up. I find no reliable information on how it works or what it contains.

**Comment by lucasgranberg** [comment]
https://github.com/lucasgranberg/lorawan-pilot/blob/master/src/main.rs

**Comment by tcpipchip** [comment]
hi lucas
got this
![image](https://github.com/lucasgranberg/lorawan-pilot/assets/11488460/cf1ef02a-31c0-4b04-8745-41147ed00402)

**Comment by tcpipchip** [comment]
![image](https://github.com/lucasgranberg/lorawan-pilot/assets/11488460/f8a05960-b3ca-4c2b-8f31-c7d0fdbec59a)

**Comment by lucasgranberg** [comment]
The problem is that the lorawan version is not the newest. I pushed a change to the main branch of lorawan-pilot that defines the lorawan version by rev. Try pulling the newest version of lorawan-pilot.

**Comment by tcpipchip** [comment]
can you remember the git command sintax to do this :)

**Comment by lucasgranberg** [comment]
in the root directory of the lorawan-pilot code try
```sh
git stash
git pull
git stash pop
```
The stash stuff you only need if you did changes that you want to keep

You could also try to use built in git in vscode. There are buttons to help you do this.

This guide might help you
https://rogerdudler.github.io/git-guide/

**Comment by tcpipchip** [comment]
Lucas
Did you get sucess on your side on compile !

**Comment by tcpipchip** [comment]
good morning!
got this
![image](https://github.com/lucasgranberg/lorawan-pilot/assets/11488460/233d98cb-2112-4806-a642-ceae59633570)

**Comment by tcpipchip** [comment]
![image](https://github.com/lucasgranberg/lorawan-pilot/assets/11488460/3b00a995-6bf0-4665-b6d5-158c74ba1378)

**Comment by lucasgranberg** [comment]
that is because you are compiling without the --release flag so the bin becomes too big to fit. `cargo build --release` to get a smaller binary size.

That being said, stop using github issues as a place to request support. These problems could have been solved by just reading the error messages and trying to understand what they mean.

**Comment by tcpipchip** [comment]
yes, i had understand the error...i changed the .cargo config to see if was to the correct processor...but...neve had imagine that was a space problem with RUST.
ok,i will investigate more before sending questions....
thank you again!

**Comment by lucasgranberg** [comment]
Read this before asking more questions or at least check if the answer is here
https://docs.rust-embedded.org/book/
for binary size look at 
https://docs.rust-embedded.org/book/unsorted/speed-vs-size.html
